plugins {
    id 'net.fabricmc.fabric-loom'
}

base {
    archivesName = "${mod_id}-${minecraft_version}-fabric"
}

sourceSets.main {
    java.srcDir project(':common').file('src/main/java')
    resources.srcDir project(':common').file('src/main/resources')
}

// 导入本地测试资源集
sourceSets {
    localTest {
        java.srcDir project(':common').file('src/localTest/java')
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += output + compileClasspath
    }
}
// 配置 runClient 任务以依赖 localTestClasses，并将其输出添加到 classpath
tasks.matching { it.name == 'runClient' }.configureEach {
    dependsOn tasks.named('localTestClasses')
    classpath.from(sourceSets.localTest.output)
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation(include("com.electronwill.night-config:core:${night_config_version}"))
    implementation(include("com.electronwill.night-config:toml:${night_config_version}"))

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

processResources {
    def values = [
            version: project.version,
            minecraft_version: minecraft_version,
            fabric_loader_version: fabric_loader_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license
    ]
    inputs.properties values
    filteringCharset = 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand values
    }
}
