plugins {
    id 'java-library'
    id 'net.minecraftforge.gradle'
    id 'net.minecraftforge.renamer'
}

base {
    archivesName = "${mod_id}-${minecraft_version}-forge"
}

sourceSets.main {
    java.srcDir project(':common').file('src/main/java')
    resources.srcDir project(':common').file('src/main/resources')
}

tasks.named('compileJava', JavaCompile).configure {
    destinationDirectory = layout.buildDirectory.dir('classes/java/main')
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }
        register('client')
        register('server') { args '--nogui' }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_version}")
}

renamer.mappings.from minecraft.dependency.toSrgFile

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def values = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_loader_version_range: forge_loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version
    ]
    inputs.properties values
    expand values
    from 'src/main/templates'
    into layout.buildDirectory.dir('generated/sources/modMetadata')
}

sourceSets.main.resources.srcDir generateModMetadata

tasks.named('jar', Jar).configure {
    from tasks.named('compileJava').flatMap { it.destinationDirectory }
}

def renameJar = renamer.classes(tasks.named('jar', Jar))

tasks.named('assemble').configure {
    dependsOn renameJar
}
