plugins {
    id 'net.fabricmc.fabric-loom-remap'
}

base {
    archivesName = "${mod_id}-common"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def exportNamedMinecraft = tasks.register('exportNamedMinecraft', Copy) {
    from({ configurations.compileClasspath.filter { it.name.startsWith('minecraft-merged-') } })
    into layout.buildDirectory.dir('namedMinecraft')
    rename { 'minecraft-named.jar' }
}

configurations.create('namedMinecraftElements') {
    canBeConsumed = true
    canBeResolved = false
}

artifacts.add('namedMinecraftElements', layout.buildDirectory.file('namedMinecraft/minecraft-named.jar')) {
    builtBy exportNamedMinecraft
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
